name: genesis_env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py37_0
  - google-pasta=0.1.7=py_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - intel-openmp=2019.3=199
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.8.0=hd408876_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - markdown=3.1.1=py37_0
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1c=h7b6447c_1
  - pillow=6.0.0=py36h34e0f95_0
  - pip=19.2.2=py37_0
  - protobuf=3.8.0=py37he6710b0_0
  - pycparser=2.19=py37_0
  - python=3.7.4=h265db76_1
  - readline=7.0=h7b6447c_5
  - scipy=1.2.1=py37h7c811a0_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorflow=1.14.0=mkl_py37h45c423b_0
  - tensorflow-base=1.14.0=mkl_py37h7ce6ba3_0
  - tensorflow-estimator=1.14.0=py_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hbc83047_0
  - werkzeug=0.15.5=py_0
  - wheel=0.33.4=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.0.1=py3.7_cuda10.0.130_cudnn7.4.2_2
  - torchvision=0.2.2=py_3
  - pip:
    - attrdict==2.0.1
    - cycler==0.10.0
    - imageio==2.5.0
    - joblib==0.13.2
    - kiwisolver==1.1.0
    - matplotlib==3.1.1
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - scikit-learn==0.21.3
    - simplejson==3.16.0
    - sklearn==0.0
    - tensorboardx==1.8
    - torch==1.0.1.post2
    - tqdm==4.36.1
