name: genesis_env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.8.1=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.3.2=py_0
  - glib=2.63.1=h5a9c865_0
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.6.1=py37_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_3
  - pcre=8.43=he6710b0_0
  - pillow=6.2.1=py37h34e0f95_0
  - pip=19.3.1=py37_0
  - pycparser=2.19=py37_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.3.2=py37h7c811a0_0
  - setuptools=42.0.2=py37_0
  - simplejson=3.17.0=py37h7b6447c_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorflow=1.14.0=mkl_py37h45c423b_0
  - tensorflow-base=1.14.0=mkl_py37h7ce6ba3_0
  - tensorflow-estimator=1.14.0=py_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.2=py37_cu101
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.40.2=py_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - argcomplete==1.11.0
    - attrdict==2.0.1
    - boto==2.49.0
    - crcmod==1.7
    - cryptography==2.8
    - fasteners==0.15
    - gcs-oauth2-boto-plugin==2.5
    - google-apitools==0.5.30
    - google-reauth==0.1.0
    - gsutil==4.46
    - httplib2==0.15.0
    - importlib-metadata==1.3.0
    - joblib==0.14.1
    - mock==2.0.0
    - monotonic==1.5
    - more-itertools==8.0.2
    - oauth2client==4.1.3
    - pbr==5.4.4
    - protobuf==3.11.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.7
    - pyopenssl==19.1.0
    - pyu2f==0.1.4
    - retry-decorator==1.1.0
    - rsa==4.0
    - scikit-learn==0.22
    - sklearn==0.0
    - socksipy-branch==1.1
    - tensorboardx==1.9
    - zipp==0.6.0
prefix: /opt/conda/envs/genesis_env